#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

for FILE in custom.d/*.sh
do
  source ${FILE}
done

exec /usr/sbin/nginx

pushd /srv/www > /dev/null
exec /usr/sbin/nginx
popd > /dev/null
