#!/bin/bash

if [ -f ./setup ]
then
  source ./setup
fi

if [ -f ./custom ]
then
  source ./custom
fi

if [ -d ./custom.d ]
then
  for FILE in ./custom.d/*.sh
  do
    source ${FILE}
  done
fi

pushd /srv/www > /dev/null
  exec /usr/sbin/nginx
popd > /dev/null
