#!/bin/bash
source /usr/bin/entrypoint

echo "> writing nginx config"
/usr/bin/templater -d -p nginx -o /etc/nginx/nginx.conf /etc/templates/nginx.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> writing host config"
/usr/bin/templater -d -p nginx -o /etc/nginx/host.conf /etc/templates/host.conf.tmpl

if [[ $? -ne 0 ]]
then
  /bin/s6-svscanctl -t /etc/s6
  exit 1
fi

echo "> chown webroot files"
find /srv/www \( \! -user nginx -o \! -group nginx \) -print0 | xargs -0 -r chown nginx:nginx

echo "> chown nginx files"
find /var/lib/nginx \( \! -user nginx -o \! -group nginx \) -print0 | xargs -0 -r chown nginx:nginx
