#!/bin/bash
source /usr/bin/entrypoint

if [[ "${NGINX_SKIP_TEMPLATES}" != "true" ]]
then
  echo "> writing nginx config"
  /usr/bin/gomplate -V \
    -o /etc/nginx/nginx.conf \
    -f /etc/templates/nginx.conf.tmpl

  if [[ $? -ne 0 ]]
  then
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi

  echo "> writing host config"
  /usr/bin/gomplate -V \
    -o /etc/nginx/host.conf \
    -f /etc/templates/host.conf.tmpl

  if [[ $? -ne 0 ]]
  then
    /bin/s6-svscanctl -t /etc/s6
    exit 1
  fi
fi

if [[ "${NGINX_SKIP_CHOWN}" != "true" ]]
then
  echo "> chown webroot files"
  find ${NGINX_WEBROOT} \( \! -user nginx -o \! -group nginx \) -print0 | xargs -0 -r chown nginx:nginx
fi

echo "> chown nginx files"
find /var/lib/nginx \( \! -user nginx -o \! -group nginx \) -print0 | xargs -0 -r chown nginx:nginx
