FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:8253d93cf993bf7d69fcacebb3da4454d5b138325ddf51a0881df39b0df86007

VOLUME ["/etc/nginx/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 nginx && \
  useradd -u 1000 -d /srv/www -g nginx -s /bin/bash -M nginx && \
  apk add nginx mailcap && \
  rm -rf /var/cache/apk/* /etc/nginx/*

COPY ./overlay /
