FROM ghcr.io/dockhippie/alpine:latest-arm64@sha256:769a99d0c749716671de8bae2d62d978046cbb66afdd52d8ec25c8f9b559c1bb

VOLUME ["/etc/nginx/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 nginx && \
  useradd -u 1000 -d /srv/www -g nginx -s /bin/bash -M nginx && \
  apk add nginx mailcap && \
  rm -rf /var/cache/apk/* /etc/nginx/*

COPY ./overlay /
