FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:99ec4c02eb520d5cabdcba4bf7dab807b3a2c3392a25fd86c0818565fa3623a7

VOLUME ["/etc/nginx/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 nginx && \
  useradd -u 1000 -d /srv/www -g nginx -s /bin/bash -M nginx && \
  apk add nginx mailcap && \
  rm -rf /var/cache/apk/* /etc/nginx/*

COPY ./overlay /
