FROM ghcr.io/dockhippie/alpine:latest-arm@sha256:e96ea8287d1891ed7ffd4986d10a98000ba4c0e6ffe53b16c9e117fb8e5bc096

VOLUME ["/etc/nginx/custom.d"]
EXPOSE 8080

WORKDIR /srv/www
CMD ["/usr/bin/container"]

RUN apk update && \
  apk upgrade && \
  groupadd -g 1000 nginx && \
  useradd -u 1000 -d /srv/www -g nginx -s /bin/bash -M nginx && \
  apk add nginx mailcap && \
  rm -rf /var/cache/apk/* /etc/nginx/*

COPY ./overlay /
